### ISSUE TITLE
Docker image does not work

### ISSUE THREAD

**Issue by ayZagen** [nosinovacao/floki#1]
Following error occurs when trying to start docker image:
```bash
standard_init_linux.go:219: exec user process caused: no such file or directory
```

**Comment by suvl** [comment]
@ayZagen yap, there was something fishy with the image, probably 'cause of the unfinished work on having it statically linked and slim (`-tags static_all`). I've built a new image tagged `:1.0.1` and it seems to work now. Can you try again?

**Comment by ayZagen** [comment]
It seems working now, thanks
